using System;
using System.Diagnostics;
using System.Diagnostics.Tracing;
using System.Text;
using Microsoft.Diagnostics.Tracing;
using Address = System.UInt64;

#pragma warning disable 1591        // disable warnings on XML comments not being present

// This code was automatically generated by the TraceParserGen tool, which converts
// an ETW event manifest into strongly typed C# classes.
namespace Microsoft.Diagnostics.Tracing.Parsers
{
    using Microsoft.Diagnostics.Tracing.Parsers.MicrosoftWindowsRPC;

    [System.CodeDom.Compiler.GeneratedCode("traceparsergen", "2.0")]
    public sealed class MicrosoftWindowsRPCTraceEventParser : TraceEventParser 
    {
        public static string ProviderName = "Microsoft-Windows-RPC";
        public static Guid ProviderGuid = new Guid(unchecked((int) 0x6ad52b32), unchecked((short) 0xd609), unchecked((short) 0x4be9), 0xae, 0x07, 0xce, 0x8d, 0xae, 0x93, 0x7e, 0x39);

        public MicrosoftWindowsRPCTraceEventParser(TraceEventSource source) : base(source) {}

        public event Action<RpcClientCallStartArgs> RpcClientCallStart
        {
            add
            {
                source.RegisterEventTemplate(RpcClientCallStartTemplate(value));
            }
            remove
            {
                source.UnregisterEventTemplate(value, 5, ProviderGuid);
            }
        }
        public event Action<RpcClientCallErrorArgs> RpcClientCallError
        {
            add
            {
                source.RegisterEventTemplate(RpcClientCallErrorTemplate(value));
            }
            remove
            {
                source.UnregisterEventTemplate(value, 1, ProviderGuid);
            }
        }
        public event Action<RpcCallStopArgs> RpcClientCallStop
        {
            add
            {
                source.RegisterEventTemplate(RpcClientCallStopTemplate(value));
            }
            remove
            {
                source.UnregisterEventTemplate(value, 7, ProviderGuid);
            }
        }
        public event Action<RpcServerCallBlockedArgs> RpcServerCall
        {
            add
            {
                source.RegisterEventTemplate(RpcServerCallBlockedTemplate(value));
            }
            remove
            {
                source.UnregisterEventTemplate(value, 2, ProviderGuid);
            }
        }
        public event Action<RpcServerCallStartArgs> RpcServerCallStart
        {
            add
            {
                source.RegisterEventTemplate(RpcServerCallStartTemplate(value));
            }
            remove
            {
                source.UnregisterEventTemplate(value, 6, ProviderGuid);
            }
        }
        public event Action<RpcCallStopArgs> RpcServerCallStop
        {
            add
            {
                source.RegisterEventTemplate(RpcServerCallStopTemplate(value));
            }
            remove
            {
                source.UnregisterEventTemplate(value, 8, ProviderGuid);
            }
        }
        public event Action<RpcCallStopArgs> RpcException
        {
            add
            {
                source.RegisterEventTemplate(RpcCallException(value));
            }
            remove
            {
                source.UnregisterEventTemplate(value, 9, ProviderGuid);
            }
        }

        #region private
        protected override string GetProviderName() { return ProviderName; }

        static private EmptyTraceData NotUsed4(Action<EmptyTraceData> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new EmptyTraceData(action, 4, 3, "Debug", Guid.Empty, 0, "", ProviderGuid, ProviderName );
        }
        static private EmptyTraceData NotUsed10(Action<EmptyTraceData> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new EmptyTraceData(action, 10, 3, "Debug", Guid.Empty, 0, "", ProviderGuid, ProviderName );
        }
        static private EmptyTraceData NotUsed11(Action<EmptyTraceData> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new EmptyTraceData(action, 11, 3, "Debug", Guid.Empty, 0, "", ProviderGuid, ProviderName );
        }
        static private EmptyTraceData NotUsed12(Action<EmptyTraceData> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new EmptyTraceData(action, 12, 3, "Debug", Guid.Empty, 1, "Start", ProviderGuid, ProviderName );
        }
        static private EmptyTraceData NotUsed13(Action<EmptyTraceData> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new EmptyTraceData(action, 13, 3, "Debug", Guid.Empty, 2, "Stop", ProviderGuid, ProviderName );
        }
        static private EmptyTraceData NotUsed14(Action<EmptyTraceData> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new EmptyTraceData(action, 14, 4, "FunctionTrace", Guid.Empty, 1, "Start", ProviderGuid, ProviderName );
        }
        static private EmptyTraceData NotUsed16(Action<EmptyTraceData> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new EmptyTraceData(action, 16, 4, "FunctionTrace", Guid.Empty, 1, "Start", ProviderGuid, ProviderName );
        }
        static private EmptyTraceData NotUsed15(Action<EmptyTraceData> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new EmptyTraceData(action, 15, 4, "FunctionTrace", Guid.Empty, 2, "Stop", ProviderGuid, ProviderName );
        }
        static private RpcClientCallStartArgs RpcClientCallStartTemplate(Action<RpcClientCallStartArgs> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new RpcClientCallStartArgs(action, 5, 1, "RpcClientCall", Guid.Empty, 1, "Start", ProviderGuid, ProviderName );
        }
        static private RpcClientCallErrorArgs RpcClientCallErrorTemplate(Action<RpcClientCallErrorArgs> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new RpcClientCallErrorArgs(action, 1, 1, "RpcClientCall", Guid.Empty, 2, "Stop", ProviderGuid, ProviderName );
        }
        static private RpcCallStopArgs RpcClientCallStopTemplate(Action<RpcCallStopArgs> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new RpcCallStopArgs(action, 7, 1, "RpcClientCall", Guid.Empty, 2, "Stop", ProviderGuid, ProviderName );
        }
        static private RpcServerCallBlockedArgs RpcServerCallBlockedTemplate(Action<RpcServerCallBlockedArgs> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new RpcServerCallBlockedArgs(action, 2, 2, "RpcServerCall", Guid.Empty, 0, "", ProviderGuid, ProviderName );
        }
        static private RpcServerCallStartArgs RpcServerCallStartTemplate(Action<RpcServerCallStartArgs> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new RpcServerCallStartArgs(action, 6, 2, "RpcServerCall", Guid.Empty, 1, "Start", ProviderGuid, ProviderName );
        }
        static private RpcCallStopArgs RpcServerCallStopTemplate(Action<RpcCallStopArgs> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new RpcCallStopArgs(action, 8, 2, "RpcServerCall", Guid.Empty, 2, "Stop", ProviderGuid, ProviderName );
        }
        static private EmptyTraceData NotUsed0(Action<EmptyTraceData> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new EmptyTraceData(action, 3, 0, "task_0", Guid.Empty, 0, "", ProviderGuid, ProviderName );
        }
        static private RpcCallStopArgs RpcCallException(Action<RpcCallStopArgs> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new RpcCallStopArgs(action, 9, 0, "task_0", Guid.Empty, 0, "", ProviderGuid, ProviderName );
        }

        static private volatile TraceEvent[] s_templates;
        protected override void EnumerateTemplates(Func<string, string, EventFilterResponse> eventsToObserve, Action<TraceEvent> callback)
        {
            if (s_templates == null)
            {
                var templates = new TraceEvent[16];
                templates[0] = RpcClientCallErrorTemplate(null);
                templates[1] = RpcServerCallBlockedTemplate(null);
                templates[2] = NotUsed0(null);
                templates[3] = NotUsed4(null);
                templates[4] = RpcClientCallStartTemplate(null);
                templates[5] = RpcServerCallStartTemplate(null);
                templates[6] = RpcClientCallErrorTemplate(null);
                templates[7] = RpcServerCallStopTemplate(null);
                templates[8] = NotUsed0(null);
                templates[9] = NotUsed4(null);
                templates[10] = NotUsed4(null);
                templates[11] = NotUsed12(null);
                templates[12] = NotUsed13(null);
                templates[13] = NotUsed14(null);
                templates[14] = NotUsed15(null);
                templates[15] = NotUsed14(null);
                s_templates = templates;
            }
            foreach (var template in s_templates)
                if (eventsToObserve == null || eventsToObserve(template.ProviderName, template.EventName) == EventFilterResponse.AcceptEvent)
                    callback(template);
        }

        #endregion
    }
}

namespace Microsoft.Diagnostics.Tracing.Parsers.MicrosoftWindowsRPC
{
    public sealed class RpcClientCallStartArgs : TraceEvent
    {
        public Guid InterfaceUuid { get { return GetGuidAt(0); } }
        public int ProcNum { get { return GetInt32At(16); } }
        public ProtocolSequences Protocol { get { return (ProtocolSequences)GetInt32At(20); } }
        public string NetworkAddress { get { return GetUnicodeStringAt(24); } }
        public string Endpoint { get { return GetUnicodeStringAt(SkipUnicodeString(24)); } }
        public string Options { get { return GetUnicodeStringAt(SkipUnicodeString(SkipUnicodeString(24))); } }
        public int AuthenticationLevel { get { return GetInt32At(SkipUnicodeString(SkipUnicodeString(SkipUnicodeString(24)))); } }
        public AuthenticationServices AuthenticationService { get { return (AuthenticationServices)GetInt32At(SkipUnicodeString(SkipUnicodeString(SkipUnicodeString(24)))+4); } }
        public ImpersonationLevels ImpersonationLevel { get { return (ImpersonationLevels)GetInt32At(SkipUnicodeString(SkipUnicodeString(SkipUnicodeString(24)))+8); } }

        #region Private
        internal RpcClientCallStartArgs(Action<RpcClientCallStartArgs> target, int eventID, int task, string taskName, Guid taskGuid, int opcode, string opcodeName, Guid providerGuid, string providerName)
            : base(eventID, task, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName)
        {
            this.m_target = target;
        }
        protected override void Dispatch()
        {
            m_target(this);
        }
        protected override void Validate()
        {
            Debug.Assert(!(Version == 1 && EventDataLength != SkipUnicodeString(SkipUnicodeString(SkipUnicodeString(24)))+12));
            Debug.Assert(!(Version > 1 && EventDataLength < SkipUnicodeString(SkipUnicodeString(SkipUnicodeString(24)))+12));
        }
        protected override Delegate Target
        {
            get { return m_target; }
            set { m_target = (Action<RpcClientCallStartArgs>) value; }
        }
        public override StringBuilder ToXml(StringBuilder sb)
        {
             Prefix(sb);
             XmlAttrib(sb, "InterfaceUuid", InterfaceUuid);
             XmlAttrib(sb, "ProcNum", ProcNum);
             XmlAttrib(sb, "Protocol", Protocol);
             XmlAttrib(sb, "NetworkAddress", NetworkAddress);
             XmlAttrib(sb, "Endpoint", Endpoint);
             XmlAttrib(sb, "Options", Options);
             XmlAttrib(sb, "AuthenticationLevel", AuthenticationLevel);
             XmlAttrib(sb, "AuthenticationService", AuthenticationService);
             XmlAttrib(sb, "ImpersonationLevel", ImpersonationLevel);
             sb.Append("/>");
             return sb;
        }

        public override string[] PayloadNames
        {
            get
            {
                if (payloadNames == null)
                    payloadNames = new string[] { "InterfaceUuid", "ProcNum", "Protocol", "NetworkAddress", "Endpoint", "Options", "AuthenticationLevel", "AuthenticationService", "ImpersonationLevel"};
                return payloadNames;
            }
        }

        public override object PayloadValue(int index)
        {
            switch (index)
            {
                case 0:
                    return InterfaceUuid;
                case 1:
                    return ProcNum;
                case 2:
                    return Protocol;
                case 3:
                    return NetworkAddress;
                case 4:
                    return Endpoint;
                case 5:
                    return Options;
                case 6:
                    return AuthenticationLevel;
                case 7:
                    return AuthenticationService;
                case 8:
                    return ImpersonationLevel;
                default:
                    Debug.Assert(false, "Bad field index");
                    return null;
            }
        }

        private event Action<RpcClientCallStartArgs> m_target;
        #endregion
    }
    public sealed class RpcClientCallErrorArgs : TraceEvent
    {
        public string ImageName { get { return GetUnicodeStringAt(0); } }
        public string ComputerName { get { return GetUnicodeStringAt(SkipUnicodeString(0)); } }
        public int PID { get { return GetInt32At(SkipUnicodeString(SkipUnicodeString(0))); } }
        // Skipping TimeStamp
        public int GeneratingComponent { get { return GetInt32At(SkipUnicodeString(SkipUnicodeString(0))+4); } }
        public int Status { get { return GetInt32At(SkipUnicodeString(SkipUnicodeString(0))+8); } }
        public int DetectionLocation { get { return GetInt16At(SkipUnicodeString(SkipUnicodeString(0))+12); } }
        public int Flags { get { return GetInt16At(SkipUnicodeString(SkipUnicodeString(0))+14); } }
        public int NumberOfParameters { get { return GetInt16At(SkipUnicodeString(SkipUnicodeString(0))+16); } }
        public long Params(int arrayIndex) { return GetInt64At(SkipUnicodeString(SkipUnicodeString(0))+18 + (arrayIndex * HostOffset(8, 0))); }

        #region Private
        internal RpcClientCallErrorArgs(Action<RpcClientCallErrorArgs> target, int eventID, int task, string taskName, Guid taskGuid, int opcode, string opcodeName, Guid providerGuid, string providerName)
            : base(eventID, task, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName)
        {
            this.m_target = target;
        }
        protected override void Dispatch()
        {
            m_target(this);
        }
        protected override void Validate()
        {
            Debug.Assert(!(Version == 1 && EventDataLength != SkipUnicodeString(SkipUnicodeString(0))+18));
            Debug.Assert(!(Version > 1 && EventDataLength < SkipUnicodeString(SkipUnicodeString(0))+18));
        }
        protected override Delegate Target
        {
            get { return m_target; }
            set { m_target = (Action<RpcClientCallErrorArgs>) value; }
        }
        public override StringBuilder ToXml(StringBuilder sb)
        {
             Prefix(sb);
             XmlAttrib(sb, "ImageName", ImageName);
             XmlAttrib(sb, "ComputerName", ComputerName);
             XmlAttrib(sb, "PID", PID);
             XmlAttrib(sb, "GeneratingComponent", GeneratingComponent);
             XmlAttrib(sb, "Status", Status);
             XmlAttrib(sb, "DetectionLocation", DetectionLocation);
             XmlAttrib(sb, "Flags", Flags);
             XmlAttrib(sb, "NumberOfParameters", NumberOfParameters);
             sb.Append("/>");
             return sb;
        }

        public override string[] PayloadNames
        {
            get
            {
                if (payloadNames == null)
                    payloadNames = new string[] { "ImageName", "ComputerName", "PID", "GeneratingComponent", "Status", "DetectionLocation", "Flags", "NumberOfParameters", "Params"};
                return payloadNames;
            }
        }

        public override object PayloadValue(int index)
        {
            switch (index)
            {
                case 0:
                    return ImageName;
                case 1:
                    return ComputerName;
                case 2:
                    return PID;
                case 3:
                    return GeneratingComponent;
                case 4:
                    return Status;
                case 5:
                    return DetectionLocation;
                case 6:
                    return Flags;
                case 7:
                    return NumberOfParameters;
                default:
                    Debug.Assert(false, "Bad field index");
                    return null;
            }
        }

        private event Action<RpcClientCallErrorArgs> m_target;
        #endregion
    }
    public sealed class RpcCallStopArgs : TraceEvent
    {
        public int Status { get { return GetInt32At(0); } }

        #region Private
        internal RpcCallStopArgs(Action<RpcCallStopArgs> target, int eventID, int task, string taskName, Guid taskGuid, int opcode, string opcodeName, Guid providerGuid, string providerName)
            : base(eventID, task, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName)
        {
            this.m_target = target;
        }
        protected override void Dispatch()
        {
            m_target(this);
        }
        protected override void Validate()
        {
            Debug.Assert(!(Version == 1 && EventDataLength != 4));
            Debug.Assert(!(Version > 1 && EventDataLength < 4));
        }
        protected override Delegate Target
        {
            get { return m_target; }
            set { m_target = (Action<RpcCallStopArgs>) value; }
        }
        public override StringBuilder ToXml(StringBuilder sb)
        {
             Prefix(sb);
             XmlAttrib(sb, "Status", Status);
             sb.Append("/>");
             return sb;
        }

        public override string[] PayloadNames
        {
            get
            {
                if (payloadNames == null)
                    payloadNames = new string[] { "Status"};
                return payloadNames;
            }
        }

        public override object PayloadValue(int index)
        {
            switch (index)
            {
                case 0:
                    return Status;
                default:
                    Debug.Assert(false, "Bad field index");
                    return null;
            }
        }

        private event Action<RpcCallStopArgs> m_target;
        #endregion
    }
    public sealed class RpcServerCallBlockedArgs : TraceEvent
    {
        public string ImangeName { get { return GetUnicodeStringAt(0); } }
        public Guid InterfaceUuid { get { return GetGuidAt(SkipUnicodeString(0)); } }
        public Guid FilterKey { get { return GetGuidAt(SkipUnicodeString(0)+16); } }

        #region Private
        internal RpcServerCallBlockedArgs(Action<RpcServerCallBlockedArgs> target, int eventID, int task, string taskName, Guid taskGuid, int opcode, string opcodeName, Guid providerGuid, string providerName)
            : base(eventID, task, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName)
        {
            this.m_target = target;
        }
        protected override void Dispatch()
        {
            m_target(this);
        }
        protected override void Validate()
        {
            Debug.Assert(!(Version == 1 && EventDataLength != SkipUnicodeString(0)+32));
            Debug.Assert(!(Version > 1 && EventDataLength < SkipUnicodeString(0)+32));
        }
        protected override Delegate Target
        {
            get { return m_target; }
            set { m_target = (Action<RpcServerCallBlockedArgs>) value; }
        }
        public override StringBuilder ToXml(StringBuilder sb)
        {
             Prefix(sb);
             XmlAttrib(sb, "ImangeName", ImangeName);
             XmlAttrib(sb, "InterfaceUuid", InterfaceUuid);
             XmlAttrib(sb, "FilterKey", FilterKey);
             sb.Append("/>");
             return sb;
        }

        public override string[] PayloadNames
        {
            get
            {
                if (payloadNames == null)
                    payloadNames = new string[] { "ImangeName", "InterfaceUuid", "FilterKey"};
                return payloadNames;
            }
        }

        public override object PayloadValue(int index)
        {
            switch (index)
            {
                case 0:
                    return ImangeName;
                case 1:
                    return InterfaceUuid;
                case 2:
                    return FilterKey;
                default:
                    Debug.Assert(false, "Bad field index");
                    return null;
            }
        }

        private event Action<RpcServerCallBlockedArgs> m_target;
        #endregion
    }
    public sealed class RpcServerCallStartArgs : TraceEvent
    {
        public Guid InterfaceUuid { get { return GetGuidAt(0); } }
        public int ProcNum { get { return GetInt32At(16); } }
        public ProtocolSequences Protocol { get { return (ProtocolSequences)GetInt32At(20); } }
        public string NetworkAddress { get { return GetUnicodeStringAt(24); } }
        public string Endpoint { get { return GetUnicodeStringAt(SkipUnicodeString(24)); } }
        public string Options { get { return GetUnicodeStringAt(SkipUnicodeString(SkipUnicodeString(24))); } }
        public int AuthenticationLevel { get { return GetInt32At(SkipUnicodeString(SkipUnicodeString(SkipUnicodeString(24)))); } }
        public AuthenticationServices AuthenticationService { get { return (AuthenticationServices)GetInt32At(SkipUnicodeString(SkipUnicodeString(SkipUnicodeString(24)))+4); } }
        public ImpersonationLevels ImpersonationLevel { get { return (ImpersonationLevels)GetInt32At(SkipUnicodeString(SkipUnicodeString(SkipUnicodeString(24)))+8); } }

        #region Private
        internal RpcServerCallStartArgs(Action<RpcServerCallStartArgs> target, int eventID, int task, string taskName, Guid taskGuid, int opcode, string opcodeName, Guid providerGuid, string providerName)
            : base(eventID, task, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName)
        {
            this.m_target = target;
        }
        protected override void Dispatch()
        {
            m_target(this);
        }
        protected override void Validate()
        {
            Debug.Assert(!(Version == 1 && EventDataLength != SkipUnicodeString(SkipUnicodeString(SkipUnicodeString(24)))+12));
            Debug.Assert(!(Version > 1 && EventDataLength < SkipUnicodeString(SkipUnicodeString(SkipUnicodeString(24)))+12));
        }
        protected override Delegate Target
        {
            get { return m_target; }
            set { m_target = (Action<RpcServerCallStartArgs>) value; }
        }
        public override StringBuilder ToXml(StringBuilder sb)
        {
             Prefix(sb);
             XmlAttrib(sb, "InterfaceUuid", InterfaceUuid);
             XmlAttrib(sb, "ProcNum", ProcNum);
             XmlAttrib(sb, "Protocol", Protocol);
             XmlAttrib(sb, "NetworkAddress", NetworkAddress);
             XmlAttrib(sb, "Endpoint", Endpoint);
             XmlAttrib(sb, "Options", Options);
             XmlAttrib(sb, "AuthenticationLevel", AuthenticationLevel);
             XmlAttrib(sb, "AuthenticationService", AuthenticationService);
             XmlAttrib(sb, "ImpersonationLevel", ImpersonationLevel);
             sb.Append("/>");
             return sb;
        }

        public override string[] PayloadNames
        {
            get
            {
                if (payloadNames == null)
                    payloadNames = new string[] { "InterfaceUuid", "ProcNum", "Protocol", "NetworkAddress", "Endpoint", "Options", "AuthenticationLevel", "AuthenticationService", "ImpersonationLevel"};
                return payloadNames;
            }
        }

        public override object PayloadValue(int index)
        {
            switch (index)
            {
                case 0:
                    return InterfaceUuid;
                case 1:
                    return ProcNum;
                case 2:
                    return Protocol;
                case 3:
                    return NetworkAddress;
                case 4:
                    return Endpoint;
                case 5:
                    return Options;
                case 6:
                    return AuthenticationLevel;
                case 7:
                    return AuthenticationService;
                case 8:
                    return ImpersonationLevel;
                default:
                    Debug.Assert(false, "Bad field index");
                    return null;
            }
        }

        private event Action<RpcServerCallStartArgs> m_target;
        #endregion
    }
    public enum AuthenticationServices
    {
        Negotiate = 0x9,
        NTLM = 0xa,
        SChannel = 0xe,
        Kerberos = 0x10,
        Kernel = 0x14,
    }
    public enum ImpersonationLevels
    {
        Default = 0x0,
        Anonymous = 0x1,
        Identify = 0x2,
        Impersonate = 0x3,
        Delegate = 0x4,
    }
    public enum ProtocolSequences
    {
        TCP = 0x1,
        NamedPipes = 0x2,
        LRPC = 0x3,
        RPCHTTP = 0x4,
    }
    public enum RpcHttp2ObjectTypes
    {
        SOCKET_CHANNEL = 0x1,
        PROXY_SOCKET_CHANNEL = 0x2,
        CHANNEL = 0x3,
        BOTTOM_CHANNEL = 0x4,
        IIS_CHANNEL = 0x5,
        RAW_CONNECTION = 0x6,
        INITIAL_RAW_CONNECTION = 0x7,
        IIS_SENDER_CHANNEL = 0x8,
        ENDPOINT_RECEIVER = 0x9,
        PLUG_CHANNEL = 0xa,
        CLIENT_VC = 0xb,
        SERVER_VC = 0xc,
        INPROXY_VC = 0xd,
        OUTPROXY_VC = 0xe,
        PROXY_VC = 0xf,
        CDATA_ORIGINATOR = 0x10,
        CLIENT_CHANNEL = 0x11,
        CALLBACK = 0x12,
        FLOW_CONTROL_SENDER = 0x13,
        WINHTTP_CALLBACK = 0x14,
        WINHTTP_CHANNEL = 0x15,
        WINHTTP_RAW = 0x16,
        PROXY_RECEIVER = 0x17,
        SERVER_CHANNEL = 0x18,
        FRAGMENT_RECEIVER = 0x19,
    }
    public enum SubjectTypes
    {
        ASSOC = 0x2e,
        HTTPv2 = 0x32,
        SASSOC = 0x41,
        BCACHE2 = 0x42,
        SCALL = 0x43,
        ADDRESS = 0x44,
        ENGINE = 0x45,
        CAUSAL_F = 0x46,
        GC = 0x47,
        HEAP = 0x48,
        EEINFO = 0x49,
        ALPC = 0x4c,
        RESERVED_MEM = 0x4d,
        SCONN = 0x4e,
        CORRUPT = 0x4f,
        PROVIDER = 0x50,
        SECCRED = 0x53,
        STABLE = 0x54,
        PROTOCOL = 0x57,
        CASSOC = 0x61,
        BCACHE = 0x62,
        CCALL = 0x63,
        TP_ALPC = 0x64,
        CENDPOINT = 0x65,
        TP_CALLBACK = 0x66,
        HANDLE = 0x68,
        IF = 0x69,
        TP_IO = 0x6a,
        TP_WORK = 0x6b,
        CTXHANDLE = 0x6c,
        MUTEX = 0x6d,
        CCONN = 0x6e,
        TRANS_CONN = 0x6f,
        PACKET = 0x70,
        REFOBJ = 0x72,
        SSECCTX = 0x73,
        THREAD = 0x74,
        TP_TIMER = 0x75,
        EVENT = 0x76,
        TP_WAIT = 0x77,
        EXCEPT = 0x78,
    }
}
